<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="utf-8">
    <link rel="stylesheet" href="">
    <title>Privacy Statement</title>
    <style>
        * {
            margin: 0px;
            padding: 10px;
            box-sizing: border-box;
            text-decoration: none;
            list-style: none;
            align-items: center;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            position: sticky;
        }

        .container {
            max-width: 1200px;
            background-color: white;
            margin: auto;
            border: 5px solid #E8BEAC;
            border-radius: 10px;
        }

        .container2 {
            max-width: 1200px;
            background-image: url(static/images/logo.png);
            background-size: contain;
            background-repeat: no-repeat;
            height: 50px;
            width: 100px;
        }
    </style>
</head>

<body>
    <div class="container"><div class="container2"></div>
        <h3 style="align-content: flex-end;">Privacy Statement</h3>
        <hr>
        <h2>SECTION 1 - WHAT DO WE DO WITH YOUR INFORMATION?</h2>
        When you purchase something from our store, as part of the buying and selling process, we collect the personal
        information you give us such as your name, address, phone number and email address.
        When you browse our store, we also automatically receive your computer's internet protocol (IP) address in order
        to
        provide us with information that helps us learn about your browser and operating system.
        Email marketing (if applicable): With your permission, we may send you emails about our store, new products and
        other updates.
        <h2>SECTION 2 - CONSENT</h2>
        How do you get my consent?
        When you provide us with personal information to complete a transaction, verify your credit card, place an
        order,
        allot collection time, we imply that you consent to our collecting it and using it for that specific reason
        only. If
        we ask for your personal information for a secondary reason, like marketing, we will either ask you directly for
        your expressed consent, or provide you with an opportunity to say no.
        How do I withdraw my consent?
        If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the
        continued
        collection, use or disclosure of your information, at any time, by contacting us at info@merokirana.com or call
        us
        at +44 7911 123456
        <h2>SECTION 3 - DISCLOSURE</h2>
        We may disclose your personal information if we are required by law to do so or if you violate our Terms of
        Service.
        <h2>SECTION 4 - COOKIES</h2>
        Cookies are tiny text files which identify your computer to our server as a unique user when you visit certain
        pages
        on the Site and they are stored by your Internet browser on your computer's hard drive. Cookies can be used to
        recognize your Internet Protocol address, saving you time while you are on, or want to enter, the Site. We only
        use
        cookies for your convenience in using the Site (for example to remember who you are when you want to amend your
        shopping cart without having to re-enter your email address) and not for obtaining or using any other
        information
        about you (for example targeted advertising). Your browser can be set to not accept cookies, but this would
        restrict
        your use of the Site. Please accept our assurance that our use of cookies does not contain any personal or
        private
        details and are free from viruses. If you want to find out more information about cookies, go to
        http://www.allaboutcookies.org or to find out about removing them from your browser, go to
        http://www.allaboutcookies.org/manage-cookies/index.html. This website uses Google Analytics, a web analytics
        service provided by Google, Inc. (""Google""). Google Analytics uses cookies, which are text files placed on
        your
        computer, to help the website analyze how users use the site.<br> The information generated by the cookie about your
        use
        of the website (including your IP address) will be transmitted to and stored by Google on servers in the United
        States.<br><br> Google will use this information for the purpose of evaluating your use of the website, compiling
        reports on
        website activity for website operators and providing other services relating to website activity and internet
        usage.
        Google may also transfer this information to third parties where required to do so by law, or where such third
        parties process the information on Google's behalf. Google will not associate your IP address with any other
        data
        held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however
        please note that if you do this you may not be able to use the full functionality of this website. By using this
        website, you consent to the processing of data about you by Google in the manner and for the purposes set out
        above.
        <h2>SECTION 5 - THIRD-PARTY SERVICES</h2>
        In general, we may disclose personal information to third parties. This disclosure may be required for us to
        provide
        you access to our Services, for fulfillment of your orders, or for enhancing your experience, or to comply with
        our
        legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to
        prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our Services. We do not
        disclose your personal information to third parties for their marketing and advertising purposes without your
        explicit consent.
        We may pass your details to other companies in our group. We may also pass your details to our agents and
        subcontractors to help us with any of our uses of your data set out in our Privacy Policy. For example, we may
        use
        third parties to assist us to analyze data and to provide us with marketing or customer service assistance.
        <br><br>We may disclose personal information if required to do so by law or in the good faith belief that such
        disclosure is
        reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal
        information to law enforcement offices, third party rights owners, or others in the good faith belief that such
        disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an
        advertisement,
        posting or other content violates the rights of a third party; or protect the rights, property or personal
        safety of
        our users or the general public.<br><br>
        However, certain third-party service providers such as payment gateways and other payment transaction
        processors,
        requires information about your phone number and apps installed on the device in order to ensure secure and
        successful payment and have their own privacy policies in respect to the information we are required to provide
        to
        them for your purchase-related transactions. For these providers, we recommend that you read their privacy
        policies
        so you can understand the manner in which your personal information will be handled by these providers.
        In particular, remember that certain providers may be located in or have facilities that are located a different
        jurisdiction than either you or us. <br><br>So if you elect to proceed with a transaction that involves the services of
        a
        third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in
        which
        that service provider or its facilities are located.
        As an example, if you are located in Canada and your transaction is processed by a payment gateway located in
        the
        United States, then your personal information used in completing that transaction may be subject to disclosure
        under
        United States legislation, including the Patriot Act. Once you leave our store's website or are redirected to a
        third-party website or application, you are no longer governed by this Privacy Policy or our website's Terms of
        Service.
        Links
        When you click on links on our store, they may direct you away from our site. We are not responsible for the
        privacy
        practices of other sites and encourage you to read their privacy statements.

        <h2>SECTION 6 - SECURITY</h2>
        To protect your personal information, we take reasonable precautions and follow industry best practices to make
        sure
        it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.
        If you provide us with your credit card information, the information is encrypted using secure socket layer
        technology (SSL).
        <h2>SECTION 7 - AGE OF CONSENT</h2>
        By using this site, you represent that you are at least the age of majority in your state or province of
        residence,
        or that you are the age of majority in your state or province of residence and you have given us your consent to
        allow any of your minor dependents to use this site.
        <h2>SECTION 8 - CHANGES TO THIS PRIVACY POLICY</h2>
        We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and
        clarifications will take effect immediately upon their posting on the website. If we make material changes to
        this
        policy, we will notify you here that it has been updated, so that you are aware of what information we collect,
        how
        we use it, and under what circumstances, if any, we use and/or disclose it.
        If our store is acquired or merged with another company, your information may be transferred to the new owners
        so
        that we may continue to sell products to you.
        <h2>SECTION 9 - YOUR CONSENT</h2>
        By using the Website/app and/ or by providing your information, you consent to the collection and use of the
        information you disclose on the Website/app in accordance with this Privacy Policy, including but not limited to
        Your consent for sharing your information as per this privacy policy. If you disclose any personal information
        relating to other people to us, you represent that you have the authority to do so and to permit us to use the
        information in accordance with this Privacy Policy.
        <h2>QUESTIONS AND CONTACT INFORMATION</h2>
        If you would like to: access, correct, amend or delete any personal information we have about you, register a
        complaint, or simply want more information contact our Privacy Compliance Officer at chffreshsales2022@gmail.com

    </div>
</body>
</html>
