-- TRIGGER FOR CUSTOMER TABLE
CREATE OR REPLACE TRIGGER customer_trigger
BEFORE INSERT
ON CUSTOMER
FOR EACH ROW
BEGIN
    :new.CUSTOMER_ID:='CUST'||customer_sequence.nextval;
END;
/


-- TRIGGER FOR ADMIN TABLE
CREATE OR REPLACE TRIGGER admin_trigger
BEFORE INSERT
ON ADMIN
FOR EACH ROW
BEGIN
    :new.ADMIN_ID:='ADMIN'||admin_sequence.nextval;
END;
/


-- TRIGGER FOR TRADER TABLE
CREATE OR REPLACE TRIGGER trader_trigger
BEFORE INSERT
ON TRADER
FOR EACH ROW
BEGIN
    :new.TRADER_ID:='TRD'||trader_sequence.nextval;
END;
/


-- TRIGGER FOR DASHBOARD TABLE
CREATE OR REPLACE TRIGGER dashboard_trigger
BEFORE INSERT
ON DASHBOARD
FOR EACH ROW
BEGIN
    :new.DASHBOARD_ID:='DASH'||dashboard_sequence.nextval;
END;
/


-- TRIGGER FOR REPORT TABLE
CREATE OR REPLACE TRIGGER report_trigger
BEFORE INSERT
ON REPORT
FOR EACH ROW
BEGIN
    :new.REPORT_ID:='REP'||report_sequence.nextval;
END;
/


-- TRIGGER FOR SHOP TABLE
CREATE OR REPLACE TRIGGER shop_trigger
BEFORE INSERT
ON SHOP
FOR EACH ROW
BEGIN
    :new.SHOP_ID:='SHOP'||shop_sequence.nextval;
END;
/


-- TRIGGER FOR OFFER TABLE
CREATE OR REPLACE TRIGGER offer_trigger
BEFORE INSERT
ON OFFER
FOR EACH ROW
BEGIN
    :new.OFFER_ID:='OFF'||offer_sequence.nextval;
END;
/


-- TRIGGER FOR PRODUCT TABLE
CREATE OR REPLACE TRIGGER product_trigger
BEFORE INSERT
ON PRODUCT
FOR EACH ROW
BEGIN
    :new.PRODUCT_ID:='PROD'||product_sequence.nextval;
END;
/


-- TRIGGER FOR CART TABLE
CREATE OR REPLACE TRIGGER cart_trigger
BEFORE INSERT
ON CART
FOR EACH ROW
BEGIN
    :new.CART_ID:='CART'||cart_sequence.nextval;
END;
/


-- TRIGGER FOR ORDER_PRODUCT TABLE
CREATE OR REPLACE TRIGGER order_product_trigger
BEFORE INSERT
ON ORDER_PRODUCT
FOR EACH ROW
BEGIN
    :new.ORDER_ID:='ORD'||order_product_sequence.nextval;
END;
/


-- TRIGGER FOR BILL TABLE
CREATE OR REPLACE TRIGGER bill_trigger
BEFORE INSERT
ON BILL
FOR EACH ROW
BEGIN
    :new.BILL_ID:='BILL'||bill_sequence.nextval;
END;
/


-- TRIGGER FOR CUSTOMER_REVIEW TABLE
CREATE OR REPLACE TRIGGER customer_review_trigger
BEFORE INSERT
ON CUSTOMER_REVIEW
FOR EACH ROW
BEGIN
    :new.REVIEW_ID:='REV'||customer_review_sequence.nextval;
END;
/


-- TRIGGER FOR WISHLIST TABLE
CREATE OR REPLACE TRIGGER wishlist_trigger
BEFORE INSERT
ON WISHLIST
FOR EACH ROW
BEGIN
    :new.WISHLIST_ID:='WISH'||wishlist_sequence.nextval;
END;